### ISSUE TITLE
Le questionnaire pour la création du compte des "parents"

### ISSUE THREAD

**Issue by kmelniko** [Oedelman/projetProg#1]
J'essaie de faire le questionnaire que les parents doivent remplir pour créer un compte. Pour le moment, ça marche pas super bien, mais j'ai décidé de créer un issue, pour m'assurer qu'on est pas en train de travailler sur la même chose chacun de son côté. Puis j'ai utilisé l’idée de Pierre avec o-o-o pour signaler la progression dans le questionnaire.

**Comment by kmelniko** [comment]
Si quelqu'un est aussi en train de faire cela, il faut qu'on en parle.
Si jamais, voilà sur quoi je me suis basé comme exemple - http://codepen.io/atakan/pen/gqbIz

**Comment by ipante** [comment]
Un questionnaire sous cette forme est effectivement très esthétique!

Ceci étant dit, avez-vous déjà établi un lien fonctionnel avec votre collection? Il est toujours préférable de commencer par assurer les fonctionnalités centrales (qui peuvent utiliser un module disponible sur [AtmosphereJS](https://atmospherejs.com) , puis d'améliorer la présentation dans un second temps.

**Comment by kmelniko** [comment]
C'est exactement ce que je n'ai pas tout à fait réussi pour le moment (et les animations). J'essayais de trouver quelque chose dans la documentation/tutoriels, mais j'ai pas eu énormément de temps ce week-end. C'est effectivement la partie la plus difficile et j’espère passer quelques heures sur cela dès que possible.

Merci d'attirer mon attention sur cela!

**Comment by ipante** [comment]
Un rapide [tutoriel vidéo](https://www.youtube.com/watch?v=87itlujo8u0) peut peut-être vous débloquer. Nous pourrons en parler mercredi si cela ne résout pas votre problème.

**Comment by ipante** [comment]
PS: et n'oubliez pas d'utiliser [Mongol](https://atmospherejs.com/msavin/mongol) pour tester vos insertions!

**Comment by kmelniko** [comment]
C'est fait, tout marche bien.
